#配置多数据源
spring:
  datasource:
    #用户数据库
    user:
      url: jdbc:mysql://106.15.229.91:3306/user
      username: root
      password: Qq123123
      driver-class-name: com.mysql.cj.jdbc.Driver
      initial-size: 1
      min-idle: 1
      max-active: 20
      test-on-borrow: true
      minPoolSize: 3
      maxPoolSize: 25
      maxLifetime: 20000
      borrowConnectionTimeout: 30
      loginTimeout: 30
      maintenanceInterval: 60
      maxIdleTime: 60
    #订单数据库
    order:
        url: jdbc:mysql://106.15.229.91:3306/order
        username: root
        password: Qq123123
        driver-class-name: com.mysql.cj.jdbc.Driver
        initial-size: 1
        min-idle: 1
        max-active: 20
        test-on-borrow: true
        minPoolSize: 3
        maxPoolSize: 25
        maxLifetime: 20000
        borrowConnectionTimeout: 30
        loginTimeout: 30
        maintenanceInterval: 60
        maxIdleTime: 60


    #所数据源配置 url变为jdbc-url
    #升级后的mysql驱动类，Driver位置由com.mysql.jdbc.Driver 变为com.mysql.cj.jdbc.Drive
server:
  port: 8083